### ISSUE TITLE
Coding style crash on C code

### ISSUE THREAD

**Issue by AurelienFT** [Epitech/coding-style-checker#8]
When we don't have a curly bracket that close another one in a function and this function is more than 20 lines the coding style crash.

### Code that don't crash : 

```c
void test(char const *str)
{
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    {
    return;
} 
```

### Code that crash : 
```c
void test(char const *str)
{
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    int i = 0;
    {
    return;
} 
```

The only difference between two is that the first one has 20 lines and second one has 21 lines.

I think the fact that there is no closing curly bracket that match the opening one in the 20 first lines of the function cause the crash.

**Comment by warstrolo** [comment]
Few things and remarks about the ticket.
- For begining this is not the good repository : this issue is not relevant to this repository which aims to provide both powershell and bash scripts to run the  [banana-coding-style-checker](https://github.com/Epitech/banana-coding-style-checker) repository.
- Regarding the issue that you've encountered, this does not compile so it's seems fair that a linter will crash trying to eval coding style.

**Comment by AurelienFT** [comment]
I don't think a crash should be an expected behaviour even in wired case. The first one also doesn't compile but doesn't crash.

You can move the issue if you want

**Comment by warstrolo** [comment]
> I don't think a crash should be an expected behaviour even in wired case. The first one also doesn't compile but doesn't crash.

Well many linters crash or are unable to lint if code syntax is too wierd, but I agree on the fact that it should maybe trigger an error instead of crashing.

> You can move the issue if you want

I don't have maintainer perms on both repos so I can't move issues.

**Comment by AurelienFT** [comment]
Close in favor of https://github.com/Epitech/banana-coding-style-checker/issues/5
